apiVersion: v2
name: cert-manager-webhook-bunny
description: A Helm chart for a cert-manager ACME DNS01 webhook solver for Bunny DNS
type: application
version: 1.0.1
appVersion: "1.0.0"
home: https://github.com/aardbol/cert-manager-webhook-bunny
sources:
  - https://github.com/aardbol/cert-manager-webhook-bunny
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - bunny
  - acme
  - dns01
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: aardbol