apiVersion: v1
entries:
  cert-manager-webhook-bunny:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: o0th
          email: o0th@pm.me
    apiVersion: v1
    appVersion: 1.0.2
    created: "2025-09-12T12:23:51.909782505+02:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Bunny
    digest: ff98efd1eef06520e54220ed49343b5afb40dd6d44acd12d05416fbea88c2045
    home: https://github.com/o0th/cert-manager-webhook-bunny
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - bunny
    - ACME
    - DNS01
    name: cert-manager-webhook-bunny
    urls:
    - cert-manager-webhook-bunny-1.0.2.tgz
    version: 1.0.2
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/maintainers: |
        - name: David Hidvegi
          email: david@hidvegi.xyz
    apiVersion: v1
    appVersion: 1.0.1
    created: "2025-09-12T12:23:51.909516804+02:00"
    description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge
      via Bunny
    digest: 41bdbba3a853b13b95ffe01f765c16a6348d29e9242fdc8bdeb4b8cb345e1d72
    home: https://github.com/davidhidvegi/cert-manager-webhook-bunny
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - webhook
    - letsencrypt
    - bunny
    - ACME
    - DNS01
    name: cert-manager-webhook-bunny
    urls:
    - cert-manager-webhook-bunny-1.0.1.tgz
    version: 1.0.1
generated: "2025-09-12T12:23:51.909136678+02:00"
