name: Lint Helm

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/helm/**'
      - '.github/workflows/lint-helm.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'deploy/helm/**'
      - '.github/workflows/lint-helm.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  helm-lint:
    uses: upcloud-tools/gha-actions/.github/workflows/lint-helm.yaml@c0df829cbad57268497db8cfb6174419f925b283
