name: PR Build Dependabot
on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: read
      pull-requests: write
 
    runs-on: ubuntu-24.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build (linux/amd64)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          platforms: linux/amd64
          push: false
          context: .
